<?xml version="1.0"?>

<!--
Skin configuration file. This file contains details of your project, which will
be used to configure the chosen Forrest skin.
-->

<!DOCTYPE skinconfig [

  <!ENTITY % links.att 'name CDATA #REQUIRED'>
  <!ENTITY % link.att 'name CDATA #REQUIRED href CDATA #REQUIRED'>
  <!ELEMENT skinconfig (disable-lucene?, disable-search?, disable-print-link?, disable-pdf-link?,
  disable-xml-link?, disable-compliance-links?, obfuscate-mail-links?, searchsite-domain?, searchsite-name?,
  project-name, project-description?, project-url, project-logo, group-name?, group-description?, group-url?, group-logo?,
  host-url?, host-logo?, year?, vendor?, trail?, toc?, credits?)*>
  <!ELEMENT credits (credit*)>
  <!ELEMENT credit (name, url, image?, width?, height?)>
  <!-- id uniquely identifies the tool, and role indicates its function -->
  <!ATTLIST credit id   CDATA #IMPLIED
                   role CDATA #IMPLIED>
  <!ELEMENT disable-lucene (#PCDATA)>
  <!ELEMENT disable-search (#PCDATA)>
  <!ELEMENT disable-print-link (#PCDATA)>
  <!ELEMENT disable-pdf-link (#PCDATA)>
  <!ELEMENT disable-xml-link (#PCDATA)>
  <!ELEMENT disable-compliance-links (#PCDATA)>
  <!ELEMENT obfuscate-mail-links (#PCDATA)>
  <!ELEMENT searchsite-domain (#PCDATA)>
  <!ELEMENT searchsite-name (#PCDATA)>
  <!ELEMENT project-name (#PCDATA)>
  <!ELEMENT project-description (#PCDATA)>
  <!ELEMENT project-url (#PCDATA)>
  <!ELEMENT project-logo (#PCDATA)>
  <!ELEMENT group-name (#PCDATA)>
  <!ELEMENT group-description (#PCDATA)>
  <!ELEMENT group-url (#PCDATA)>
  <!ELEMENT group-logo (#PCDATA)>
  <!ELEMENT host-url (#PCDATA)>
  <!ELEMENT host-logo (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT vendor (#PCDATA)>
  <!ELEMENT trail (link1, link2, link3, link4)>
  <!ELEMENT link1 EMPTY>
  <!-- Seems we can't use param entity refs until this is DTDified -->
  <!ATTLIST link1 name CDATA #REQUIRED href CDATA #IMPLIED>
  <!ELEMENT link2 EMPTY>
  <!ATTLIST link2 name CDATA #REQUIRED href CDATA #IMPLIED>
  <!ELEMENT link3 EMPTY>
  <!ATTLIST link3 name CDATA #REQUIRED href CDATA #IMPLIED>
  <!ELEMENT link4 EMPTY>
  <!ATTLIST link4 name CDATA #REQUIRED href CDATA #IMPLIED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT image (#PCDATA)>
  <!ELEMENT width (#PCDATA)>
  <!ELEMENT height (#PCDATA)>
  <!ELEMENT toc EMPTY>
  <!ATTLIST toc level CDATA #IMPLIED location CDATA #IMPLIED>
  ]>

<skinconfig>
  <!-- Do we want to disable the Lucene search box? -->
  <disable-lucene>true</disable-lucene>
  <!-- Do we want to disable the Google search box? -->
  <!-- Ensure not both false -->
  <disable-search>false</disable-search>

  <!-- Do we want to disable the print link? If enabled, invalid HTML 4.0.1 -->
  <disable-print-link>false</disable-print-link>
  
  <!-- Do we want to disable the PDF link? -->
  <disable-pdf-link>false</disable-pdf-link>
  
  <!-- Do we want to disable the xml source link? -->
  <!-- The xml source link makes it possible to access the xml rendition of
        the source frim the html page, and to have it generated statically.
        This can be used to enable other sites and services to reuse the
        xml format for their uses. Keep this disabled if you don't want other
        sites to easily reuse your pages.-->
  <disable-xml-link>false</disable-xml-link>

  <!-- Do we want to disable w3c compliance links? -->
  <disable-compliance-links>false</disable-compliance-links>
  
  <!-- Whether to render mailto: links unrecognisable by spam harvesters -->
  <obfuscate-mail-links>true</obfuscate-mail-links>

  <searchsite-domain>ws.apache.org</searchsite-domain>
  <searchsite-name>WS</searchsite-name>

  <!-- mandatory project logo
       skin: forrest-site renders it at the top -->
  <project-name>jUDDI</project-name>
  <project-description>jUDDI</project-description>
  <project-url>http://ws.apache.org/juddi</project-url>
  <project-logo>images/juddi.gif</project-logo>
  <!-- Alternative static image:
  <project-logo>images/project-logo.gif</project-logo> -->

  <!-- optional group logo
       skin: forrest-site renders it at the top-left corner -->
  <group-name>Apache Web Services</group-name>
  <group-description>Apache Web Services</group-description>
  <group-url>http://ws.apache.org</group-url>
  <group-logo>images/project-logo.gif</group-logo>
  <!-- Alternative static image:
  <group-logo>images/group-logo.gif</group-logo> -->

  <!-- optional host logo (e.g. sourceforge logo)
       skin: forrest-site renders it at the bottom-left corner -->
  <host-url></host-url>
  <host-logo></host-logo>

  <!-- The following are used to construct a copyright statement -->
  <year>2003</year>
  <vendor>The Apache Software Foundation</vendor>

  <!-- Some skins use this to form a 'breadcrumb trail' of links. If you don't
  want these, set the attributes to blank. The DTD purposefully requires them.
  -->
  <trail>
    <link1 name="Apache" href="http://www.apache.org/"/>
    <link2 name="WS" href="http://ws.apache.org/"/>
    <link3 name="jUDDI" href="index.html"/>
    <link4 name="" href=""/>
  </trail>

  <!-- Configure the TOC, ie the Table of Contents.
  @level
  how many "section" levels need to be included in the
  generated Table of Contents (TOC). By default, if no toc element is provided
  below, then 2 levels are included. Level 0 does not generate any TOC at all.
  @location ("page","menu","page,menu")
  Where to show the TOC.
  -->
  <toc level="2" location="page"/>

  <!-- Credits are typically rendered as a set of small clickable images in the
  page footer -->
  <credits>
    <credit>
      <name>Built with Apache Forrest</name>
      <url>http://xml.apache.org/forrest/</url>
      <image>images/built-with-forrest-button.png</image>
      <width>88</width>
      <height>31</height>
    </credit>
    <!-- A credit with @role='pdf' will have its name and url displayed in the
    PDF page's footer. -->
  </credits>

</skinconfig>
