=== JorgeFigueroa/juddi/src/java/juddi.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Authors: Steve Viens. -->

<!-- Version: 0.9.4 -->

<!-- A configuration element consists of  -->

<!ELEMENT juddi:configuration (operator?,authenticator?,datastore?,
                               uuidgen?,monitor?,cryptor?,validator?,
                               maxNameLength?,maxNameElementsAllowed?,
							   maxBusinessEntitiesPerUser?,
							   maxBusinessServicesPerBusiness?,
							   maxBindingTemplatesPerService?,
							   maxTModelsPerUser?,maxRowsLimit?,
							   http-proxy?,uddi-proxy?)>

<!--  -->     
<!--  --> 
<!--  --> 

<!ATTLIST juddi:configuration
  xmlns:juddi CDATA #FIXED "http://ws.apache.org/juddi/" 
  debug (true|false|null)  "null"
>

<!--  -->
<!ELEMENT operator (param*)>
<!ATTLIST operator
  name ID #REQUIRED
  adminEmailAddress CDATA #IMPLIED
>

<!--  -->
<!ELEMENT authenticator (param*)>
<!ATTLIST authenticator
  class CDATA #REQUIRED
>

<!--  -->
<!ELEMENT datastore (param*)>
<!ATTLIST datastore
  class CDATA #REQUIRED
>

<!--  -->
<!ELEMENT uuidgen (param*)>
<!ATTLIST uuidgen
  class CDATA #REQUIRED
>

<!--  -->
<!ELEMENT monitor (param*)>
<!ATTLIST monitor
  class CDATA #REQUIRED
>

<!--  -->
<!ELEMENT cryptor (param*)>
<!ATTLIST cryptor
  class CDATA #REQUIRED
>

<!--  -->
<!ELEMENT validator (param*)>
<!ATTLIST validator
  class CDATA #REQUIRED
>

<!--  -->
<!ELEMENT maxNameLength (#PCDATA)>

<!--  -->
<!ELEMENT maxNameElementsAllowed (#PCDATA)>

<!--  -->
<!ELEMENT maxBusinessEntitiesPerUser (#PCDATA)>

<!--  -->
<!ELEMENT maxBusinessServicesPerBusiness (#PCDATA)>

<!--  -->
<!ELEMENT maxBindingTemplatesPerService (#PCDATA)>

<!--  -->
<!ELEMENT maxTModelsPerUser (#PCDATA)>

<!--  -->
<!ELEMENT maxRowsLimit (#PCDATA)>

<!--  -->
<!ELEMENT uddi-proxy (param*)>
<!ATTLIST uddi-proxy
  soapTransport CDATA #REQUIRED
  inquiryURL CDATA #REQUIRED
  publishURL CDATA #REQUIRED
  adminURL CDATA #IMPLIED
>

<!--  -->
<!ELEMENT http-proxy EMPTY>
<!ATTLIST http-proxy
  enabled CDATA	#REQUIRED
  host CDATA #REQUIRED
  port CDATA #REQUIRED
  userName CDATA #REQUIRED
  password CDATA #REQUIRED
>

<!--  -->
<!ELEMENT param EMPTY>
<!ATTLIST param
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

=== JorgeFigueroa/juddi/src/java/juddi.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE juddi:configuration 
          SYSTEM 
          "juddi.dtd">

<juddi:configuration 
	 debug="true"
	 xmlns:juddi="http://ws.apache.org/juddi/">

	<!-- The UDDI Operator Name -->
	<operator 
		name="jUDDI.org"
		adminEmailAddress="juddi@ws.apache.org"/>
	
	<!-- Authentication module to use -->
	<authenticator class="org.apache.juddi.auth.DefaultAuthenticator">
	</authenticator>

	<!-- DataStore module currently to use -->
	<datastore class="org.apache.juddi.datastore.jdbc.JDBCDataStore">
        <!-- jUDDI DataSource to use -->
		<param name="DataSource" value="java:comp/env/jdbc/juddiDB"/>
        <!-- jUDDI JDBC Connection Properties to use
		<param name="jdbcDriver" value="com.mysql.jdbc.Driver"/>
		<param name="jdbcURL" value="jdbc:mysql://localhost/juddi"/>
		<param name="jdbcUser" value="juddi"/>
		<param name="jdbcPassword" value="juddi"/>
		<param name="jdbcMaxActive" value="10"/>
		<param name="jdbcMaxIdle" value="10"/>
		 -->
	</datastore>
	
	<!-- UUIDGen implementation to use -->
	<uuidgen class="org.apache.juddi.uuidgen.DefaultUUIDGen">
	</uuidgen>
	
	<!-- Monitor implementation to use -->
	<monitor class="org.apache.juddi.monitor.jdbc.JDBCMonitor">
	</monitor>

	<!-- Cryptor implementation to use -->
	<cryptor class="org.apache.juddi.cryptor.DefaultCryptor">
	</cryptor>
	
	<!-- Validator to use -->
	<validator class="org.apache.juddi.validator.DefaultValidator">
	</validator>

	<!-- The max size and max elements allowed in several 
	     of the FindXxxx and SaveXxxx functions. -->
	<maxNameLength>255</maxNameLength>
	<maxNameElementsAllowed>5</maxNameElementsAllowed>
	<maxBusinessEntitiesPerUser>25</maxBusinessEntitiesPerUser>
	<maxBusinessServicesPerBusiness>20</maxBusinessServicesPerBusiness>
	<maxBindingTemplatesPerService>10</maxBindingTemplatesPerService>
	<maxTModelsPerUser>100</maxTModelsPerUser>
	<maxRowsLimit>10</maxRowsLimit>

	<!--  HTTP Proxy Configuration -->
	<http-proxy 
		enabled="false"
		host="proxy.viens.net"
		port="8000"
		userName="sviens"
		password="password"/>
	
	<!-- jUDDI Proxy Configuration (used by RegistryProxy) -->
	<uddi-proxy soapTransport="org.apache.juddi.proxy.AxisTransport"
			inquiryURL="http://localhost:8080/juddi/inquiry"
			publishURL="http://localhost:8080/juddi/publish"
			adminURL="http://localhost:8080/juddi/admin">
		<param name="securityProvider" value="com.sun.net.ssl.internal.ssl.Provider"/>
		<param name="protocolHandler" value="com.sun.net.ssl.internal.www.protocol"/>		
	</uddi-proxy>

</juddi:configuration>
